create table if not exists public.terms (
  term text primary key,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists terms_one_active_idx
  on public.terms (is_active)
  where is_active;

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null,
  term text not null,
  teacher text not null default '',
  name_key text not null default '',
  payload jsonb not null,
  rmp jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists courses_name_idx on public.courses (name);
create index if not exists courses_term_idx on public.courses (term);
create index if not exists courses_name_key_idx on public.courses (name_key);

create table if not exists public.rmp_data (
  name_key text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.terms enable row level security;
alter table public.courses enable row level security;
alter table public.rmp_data enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.terms to service_role;
grant select, insert, update, delete on public.courses to service_role;
grant select, insert, update, delete on public.rmp_data to service_role;

do $$
begin
  if to_regclass('public.courses_id_seq') is not null then
    grant usage, select on sequence public.courses_id_seq to service_role;
  end if;
end $$;
